repos:
  - repo: git@github.com:pre-commit/mirrors-isort.git
    rev: v5.9.3
    hooks:
      - id: isort
  - repo: git@github.com:psf/black.git
    rev: 23.3.0
    hooks:
      - id: black
  - repo: git@github.com:pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
