services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --reload
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL_1=${DATABASE_URL}
      - REDIS_URL_1=${REDIS_URL}
      - PORT=${PORT}
    env_file:
      - .env.nonlocal

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  postgres_data:

