services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --reload
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL_1=${DATABASE_URL}
      - REDIS_URL_1=${REDIS_URL}
      - PORT=${PORT}
    volumes:
      - .:/app
    env_file:
      - .env
