"""Add correct user table

Revision ID: 342e745e3392
Revises: b3ff8b161948
Create Date: 2024-07-08 16:54:17.139613

"""
from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision: str = "342e745e3392"
down_revision: Union[str, None] = "b3ff8b161948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
