"""Add correct user table

Revision ID: 364844c2670d
Revises: c90d9dba7a84
Create Date: 2024-07-08 16:35:15.348603

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "364844c2670d"
down_revision: Union[str, None] = "c90d9dba7a84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("firstname", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("lastname", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("city", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("avatar", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    op.drop_column("users", "role")
    op.drop_column("users", "username")
    op.drop_column("users", "info")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("info", sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "avatar")
    op.drop_column("users", "phone")
    op.drop_column("users", "city")
    op.drop_column("users", "lastname")
    op.drop_column("users", "firstname")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
