"""Add companies table

Revision ID: af9902c26b01
Revises: bd6fceb97f80
Create Date: 2024-07-20 18:33:00.842138

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "af9902c26b01"
down_revision: Union[str, None] = "bd6fceb97f80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
