"""Add correct user table

Revision ID: b3ff8b161948
Revises: 364844c2670d
Create Date: 2024-07-08 16:50:49.575274

"""
from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3ff8b161948"
down_revision: Union[str, None] = "364844c2670d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
