"""Add auth

Revision ID: bbc4fd299a2f
Revises: 6669232a0669
Create Date: 2024-07-10 13:43:06.956480

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbc4fd299a2f"
down_revision: Union[str, None] = "6669232a0669"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("refresh_token", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
