name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install poetry
        poetry install

    - name: Build Docker image
      run: |
        docker build -t my-fastapi-app .

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        docker tag my-fastapi-app $DOCKER_HUB_USERNAME/my-fastapi-app:latest
        docker push $DOCKER_HUB_USERNAME/my-fastapi-app:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name python-app-container my-fastapi-app:latest
